// The room shell uses a small, local catalog. Security warnings are translated
// here with the same scope as the English source text.
export const english = {
  minutes: "Minutes",
  hours: "Hours",
  days: "Days",
  indefinite: "Indefinite",
  messageVanish: "Message vanish",
  roomSelfDestruct: "Room self-destruct",
  onlyManualDestroy: "Only manual destroy",
  idle: "idle",
  createRoom: "Create private conversation",
  creatingRoom: "Creating room...",
  roomSecret: "Room secret stays in the URL fragment and never reaches the server.",
  messagesStay: "Messages stay until someone destroys the room.",
  messagesVanish: "Messages vanish after {duration}.",
  roomStays: "Room stays open until someone destroys it.",
  roomExpires: "Room self-destructs in {duration}.",
  destroyed: "This room was destroyed and everyone was disconnected.",
  joinTimeout: "This room self-destructed because nobody joined before the room timeout.",
  inactive: "This room self-destructed after the configured idle timeout.",
  maxAge: "This room reached its maximum lifetime and self-destructed.",
  unavailable: "This room is no longer available.",
  inviteClaimed: "This one-time invite is already being used by another browser session.",
  inviteUsed: "This one-time invite has already admitted another session.",
  inviteInvalid: "This one-time invite has expired, was revoked, or is no longer available.",
  invalidLink: "Link no longer valid",
  removedTitle: "You were removed from this room",
  removedCopy: "The room creator ended your access to this conversation.",
  backHome: "Back to home",
  checkingInvite: "Checking invite",
  verifyingInvite: "Verifying this one-time invite and joining the room.",
  roomGone: "Room gone",
  roomGoneCopy: "This conversation self-destructed. Nothing was kept.",
  roomNotFound: "This room no longer exists. It may have already self-destructed.",
  startNew: "Start a new one",
  connected: "Connected",
  connecting: "Connecting",
  disconnected: "Disconnected",
  reconnecting: "Reconnecting in {seconds}s",
  closed: "Closed",
  connectionError: "Error",
  present: "{count} present",
  you: "You",
  guest: "Guest",
  waiting: "Waiting for someone to join.",
  remove: "Remove",
  newInviteExpires: "New invite expires",
  inviteNextOnly: "Applies only to the next single-use invite you create.",
  inviteLifetimeAmount: "Invite lifetime amount",
  inviteLifetimeUnit: "Invite lifetime unit",
  invites: "invites",
  inviteGuidance: "Send one unused invite to one person. Each link expires and can only be used once.",
  share: "Share",
  copyInvite: "Copy invite link",
  inviteShared: "Invite shared",
  inviteCopiedSend: "Invite copied—send it",
  sendInvite: "Send invite",
  inviteOne: "Invite one person",
  copied: "Copied",
  copyMyLink: "Copy my link",
  destroying: "Destroying...",
  destroy: "Destroy",
  inviteSharedStatus: "Invite shared.",
  inviteCopiedStatus: "Invite copied.",
  roomLinkCopiedStatus: "Room link copied.",
  deriving: "Deriving key and joining room...",
  download: "Download",
  saveFile: "Save file",
  transferFailed: "Transfer failed—ask for a re-share",
  fileShared: "Shared—peers can download",
  attachFile: "Attach an encrypted file",
  attachFileLabel: "Attach file",
  writeMessageLabel: "Write an encrypted message",
  writeMessage: "Write a message",
  roomClosed: "Room is closed",
  sendEncrypted: "Send encrypted",
  authFailed: "Message authentication failed. Check that you opened the full capability link.",
  alteredMessage: "Unsupported or altered message was rejected.",
  replayLimit: "This page reached its message limit. Open a new room to continue.",
  copiedInviteNotice: "Invite copied. Send it to one person—the link can only be used once.",
  sharedInviteNotice: "Invite handed to your selected app. The link can only be used once.",
  createdInviteNotice: "Invite created. Choose Share or Copy below when you are ready.",
  removedInviteNotice: "Invite removed.",
  inviteStatusRevoked: "revoked",
  inviteStatusJoined: "joined",
  inviteStatusJoining: "joining...",
  inviteStatusExpired: "expired",
  inviteStatusExpires: "expires in {duration}",
  tryInvite: "Try the invite loop yourself: ",
  madeWith: "This disposable room was made with elm.chat. ",
  makeYourOwn: "Start your own room and invite one person—free, no signup.",
  peerDestroyed: "A connected peer destroyed this room.",
  fileTooLarge: "\"{name}\" is larger than the {limit} limit.",
  fileDeliveryPending: "File shared locally, but delivery to other participants is not ready yet.",
  fileRequestFailed: "Could not reach the sender to start the download.",
  missingSecret: "Missing room secret in the URL fragment.",
  messageDeliveryPending: "Message saved locally, but room transport is not ready yet.",
  messageDeliveryFailed: "Message saved locally, but delivery to other participants failed.",
  clipboardLinkFailed: "Clipboard access is blocked in this browser context. Copy the link manually from the address bar.",
  clipboardInviteFailed: "Clipboard access is blocked in this browser context. Copy the invite URL manually.",
  createInviteFailed: "Failed to create invite.",
  revokeInviteFailed: "Failed to revoke invite.",
  destroyRoomFailed: "Failed to destroy room.",
  shareMenuFailed: "This browser could not open its share menu. Copy the invite instead.",
  inviteCopyBelow: "Invite created. Copy it below and send it to one person.",
  inviteShareText: "Join my disposable elm.chat room. This single-use link expires.",
  vanishesIn: "Vanishes in {duration}",
  untilRoomCloses: "Available until the room closes",
  participants: "Participants",
  inviteExpiration: "Invite expiration",
  securityStatus: "Security status",
  securityWarning: "Not independently audited. The relay sees connection metadata, and participants can retain plaintext.",
  communityTitle: "GitHub project activity",
  latestFixes: "Latest fixes",
  openRequests: "Open requests",
  viewAll: "View all",
  noFixes: "No recent fixes yet.",
  noRequests: "No open requests right now.",
  loadingCommunity: "Loading GitHub activity...",
  communityUnavailable: "GitHub activity is unavailable right now.",
  viewOnGithub: "View on GitHub",
  whyUse: "Why use this?",
  readArticle: "Read the article",
  pressKit: "Press kit",
  learnAbout: "Learn about elm chat",
  heroTitle: "Instant chat. Account-free, encrypted, fast and disposable.",
  heroCopy: "Encrypted link-based chat with color identity, no usernames, and room rules you set before anyone joins.",
  githubHeadline: "Star or inspect on GitHub",
  githubCopy: "Open source. Review every claim, fork it, or help build it.",
  githubStats: "GitHub stars and forks",
  projectSource: "Project source",
  viewSource: "View source",
  forkMe: "Fork me",
  starterIssue: "Pick a starter issue",
  access: "Access",
  secretLinkOnly: "Secret link only",
  messagePolicy: "Message policy",
  roomPolicy: "Room policy",
  manualCleanup: "Manual cleanup",
  noIdleTimeout: "No idle timeout",
  idleSelfDestruct: "Idle self-destruct",
  unableCreateRoom: "Unable to create room.",
  failedCreateRoom: "Failed to create room.",
  failedLoadInvites: "Failed to load invites.",
  roomNotFoundError: "Room not found.",
  failedJoinRoom: "Failed to join room.",
  freshcodeFound: "Found via Freshcode",
  freshcodeOpen: "elm.chat v0.1.0 is open for inspection.",
  freshcodeCopy: "Try a short-lived room below, review the documented limits, or deploy your own Cloudflare instance. This early release has not had an independent security audit.",
  inspectRelease: "Inspect v0.1.0",
  deployOwn: "Deploy your own"
} as const;

export type MessageKey = keyof typeof english;
export type Locale = "en" | "es";

export const spanish: Record<MessageKey, string> = {
  minutes: "Minutos",
  hours: "Horas",
  days: "Días",
  indefinite: "Indefinido",
  messageVanish: "Los mensajes desaparecen",
  roomSelfDestruct: "Autodestrucción de la sala",
  onlyManualDestroy: "Solo destrucción manual",
  idle: "de inactividad",
  createRoom: "Crear conversación privada",
  creatingRoom: "Creando sala...",
  roomSecret: "El secreto de la sala permanece en el fragmento de la URL y nunca llega al servidor.",
  messagesStay: "Los mensajes permanecen hasta que alguien destruye la sala.",
  messagesVanish: "Los mensajes desaparecen después de {duration}.",
  roomStays: "La sala permanece abierta hasta que alguien la destruye.",
  roomExpires: "La sala se autodestruye en {duration}.",
  destroyed: "Esta sala se destruyó y todas las personas fueron desconectadas.",
  joinTimeout: "Esta sala se autodestruyó porque nadie entró antes de que venciera el plazo.",
  inactive: "Esta sala se autodestruyó tras el periodo de inactividad configurado.",
  maxAge: "Esta sala alcanzó su duración máxima y se autodestruyó.",
  unavailable: "Esta sala ya no está disponible.",
  inviteClaimed: "Otra sesión del navegador ya está usando esta invitación de un solo uso.",
  inviteUsed: "Esta invitación de un solo uso ya permitió entrar a otra sesión.",
  inviteInvalid: "Esta invitación de un solo uso caducó, fue revocada o ya no está disponible.",
  invalidLink: "El enlace ya no es válido",
  removedTitle: "Se te ha retirado de esta sala",
  removedCopy: "Quien creó la sala canceló tu acceso a esta conversación.",
  backHome: "Volver al inicio",
  checkingInvite: "Comprobando invitación",
  verifyingInvite: "Verificando esta invitación de un solo uso y entrando en la sala.",
  roomGone: "Sala desaparecida",
  roomGoneCopy: "Esta conversación se autodestruyó. No se conservó nada.",
  roomNotFound: "Esta sala ya no existe. Es posible que ya se haya autodestruido.",
  startNew: "Iniciar otra",
  connected: "Conectado",
  connecting: "Conectando",
  disconnected: "Desconectado",
  reconnecting: "Reconectando en {seconds}s",
  closed: "Cerrado",
  connectionError: "Error",
  present: "{count} presentes",
  you: "Tú",
  guest: "Invitado",
  waiting: "Esperando a que alguien entre.",
  remove: "Eliminar",
  newInviteExpires: "La nueva invitación caduca",
  inviteNextOnly: "Se aplica solo a la próxima invitación de un solo uso que crees.",
  inviteLifetimeAmount: "Duración de la invitación",
  inviteLifetimeUnit: "Unidad de duración de la invitación",
  invites: "invitaciones",
  inviteGuidance: "Envía una invitación sin usar a una sola persona. Cada enlace caduca y solo puede usarse una vez.",
  share: "Compartir",
  copyInvite: "Copiar enlace de invitación",
  inviteShared: "Invitación compartida",
  inviteCopiedSend: "Invitación copiada: envíala",
  sendInvite: "Enviar invitación",
  inviteOne: "Invitar a una persona",
  copied: "Copiado",
  copyMyLink: "Copiar mi enlace",
  destroying: "Destruyendo...",
  destroy: "Destruir",
  inviteSharedStatus: "Invitación compartida.",
  inviteCopiedStatus: "Invitación copiada.",
  roomLinkCopiedStatus: "Enlace de la sala copiado.",
  deriving: "Derivando la clave y entrando en la sala...",
  download: "Descargar",
  saveFile: "Guardar archivo",
  transferFailed: "Transferencia fallida: pide que lo compartan de nuevo",
  fileShared: "Compartido: otros participantes pueden descargarlo",
  attachFile: "Adjuntar un archivo cifrado",
  attachFileLabel: "Adjuntar archivo",
  writeMessageLabel: "Escribir un mensaje cifrado",
  writeMessage: "Escribe un mensaje",
  roomClosed: "La sala está cerrada",
  sendEncrypted: "Enviar cifrado",
  authFailed: "Falló la autenticación del mensaje. Comprueba que abriste el enlace completo.",
  alteredMessage: "Se rechazó un mensaje no compatible o alterado.",
  replayLimit: "Esta página alcanzó el límite de mensajes. Abre una sala nueva para continuar.",
  copiedInviteNotice: "Invitación copiada. Envíala a una persona: el enlace solo puede usarse una vez.",
  sharedInviteNotice: "Invitación enviada a la aplicación elegida. El enlace solo puede usarse una vez.",
  createdInviteNotice: "Invitación creada. Elige Compartir o Copiar cuando quieras.",
  removedInviteNotice: "Invitación eliminada.",
  inviteStatusRevoked: "revocada",
  inviteStatusJoined: "usada",
  inviteStatusJoining: "entrando...",
  inviteStatusExpired: "caducada",
  inviteStatusExpires: "caduca en {duration}",
  tryInvite: "Prueba el ciclo de invitación: ",
  madeWith: "Esta sala temporal se creó con elm.chat. ",
  makeYourOwn: "Crea tu propia sala e invita a una persona: gratis y sin registro.",
  peerDestroyed: "Una persona conectada destruyó esta sala.",
  fileTooLarge: "\"{name}\" supera el límite de {limit}.",
  fileDeliveryPending: "El archivo se compartió localmente, pero aún no se puede entregar a otras personas.",
  fileRequestFailed: "No se pudo contactar a quien envió el archivo para iniciar la descarga.",
  missingSecret: "Falta el secreto de la sala en el fragmento de la URL.",
  messageDeliveryPending: "El mensaje se guardó localmente, pero la conexión de la sala aún no está lista.",
  messageDeliveryFailed: "El mensaje se guardó localmente, pero no se pudo entregar a otras personas.",
  clipboardLinkFailed: "El portapapeles está bloqueado en este navegador. Copia el enlace desde la barra de direcciones.",
  clipboardInviteFailed: "El portapapeles está bloqueado en este navegador. Copia manualmente la URL de invitación.",
  createInviteFailed: "No se pudo crear la invitación.",
  revokeInviteFailed: "No se pudo revocar la invitación.",
  destroyRoomFailed: "No se pudo destruir la sala.",
  shareMenuFailed: "Este navegador no pudo abrir el menú para compartir. Copia la invitación.",
  inviteCopyBelow: "Invitación creada. Cópiala abajo y envíala a una persona.",
  inviteShareText: "Entra en mi sala temporal de elm.chat. Este enlace de un solo uso caduca.",
  vanishesIn: "Desaparece en {duration}",
  untilRoomCloses: "Disponible hasta que se cierre la sala",
  participants: "Participantes",
  inviteExpiration: "Caducidad de la invitación",
  securityStatus: "Estado de seguridad",
  securityWarning: "No se ha realizado una auditoría de seguridad independiente. El servidor de retransmisión ve metadatos de conexión y quienes participan pueden conservar el texto sin cifrar.",
  communityTitle: "Actividad del proyecto en GitHub",
  latestFixes: "Correcciones recientes",
  openRequests: "Solicitudes abiertas",
  viewAll: "Ver todas",
  noFixes: "Aún no hay correcciones recientes.",
  noRequests: "No hay solicitudes abiertas ahora.",
  loadingCommunity: "Cargando actividad de GitHub...",
  communityUnavailable: "La actividad de GitHub no está disponible ahora.",
  viewOnGithub: "Ver en GitHub",
  whyUse: "¿Por qué usarlo?",
  readArticle: "Leer el artículo",
  pressKit: "Kit de prensa",
  learnAbout: "Conoce elm chat",
  heroTitle: "Chat instantáneo. Sin cuenta, cifrado, rápido y temporal.",
  heroCopy: "Chat cifrado mediante enlaces, con identidad por color, sin nombres de usuario y con reglas de sala que eliges antes de que entre nadie.",
  githubHeadline: "Apoya o inspecciona el proyecto en GitHub",
  githubCopy: "Código abierto. Revisa cada afirmación, crea tu propia versión o ayuda a desarrollarlo.",
  githubStats: "Estrellas y bifurcaciones en GitHub",
  projectSource: "Código fuente del proyecto",
  viewSource: "Ver código",
  forkMe: "Crear bifurcación",
  starterIssue: "Elegir una tarea inicial",
  access: "Acceso",
  secretLinkOnly: "Solo con enlace secreto",
  messagePolicy: "Política de mensajes",
  roomPolicy: "Política de la sala",
  manualCleanup: "Eliminación manual",
  noIdleTimeout: "Sin límite por inactividad",
  idleSelfDestruct: "Autodestrucción por inactividad",
  unableCreateRoom: "No se pudo crear la sala.",
  failedCreateRoom: "No se pudo crear la sala.",
  failedLoadInvites: "No se pudieron cargar las invitaciones.",
  roomNotFoundError: "No se encontró la sala.",
  failedJoinRoom: "No se pudo entrar en la sala.",
  freshcodeFound: "Encontrado en Freshcode",
  freshcodeOpen: "elm.chat v0.1.0 está disponible para inspección.",
  freshcodeCopy: "Prueba una sala temporal, revisa los límites documentados o despliega tu propia instancia en Cloudflare. Esta versión inicial no ha tenido una auditoría de seguridad independiente.",
  inspectRelease: "Inspeccionar v0.1.0",
  deployOwn: "Desplegar una instancia"
};

export function resolveLocale(languages: readonly string[]): Locale {
  for (const language of languages) {
    const code = language.toLowerCase().split("-")[0];
    if (code === "es") return "es";
    if (code === "en") return "en";
  }
  return "en";
}

export function translate(
  locale: Locale,
  key: MessageKey,
  values: Record<string, string | number> = {}
): string {
  const template = locale === "es" ? spanish[key] : english[key];
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}

export const locale = resolveLocale(
  typeof navigator === "undefined" ? [] : navigator.languages.length ? navigator.languages : [navigator.language]
);
export const t = (key: MessageKey, values?: Record<string, string | number>) =>
  translate(locale, key, values);
